package view;

import controller.ServicoController;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import model.PadraoNumeros;
import java.text.ParseException;
import java.util.Date;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;
import javax.swing.text.MaskFormatter;

public class FrCadastroServico extends javax.swing.JFrame {

    private boolean flagCancelar;
    private boolean flagEdtSalvar;
    ServicoController servicoController;
    private Object [] servico;
    private ArrayList<Object []> arrayServico = new ArrayList<>();
    
    public FrCadastroServico(ServicoController servicoController) throws ParseException {
        initComponents();
        setExtendedState(java.awt.Frame.MAXIMIZED_BOTH);//Maximizar
        this.formatarCampos();
        this.setVisible(true);
        this.servicoController = servicoController;
        this.flagCancelar = false;
        this.flagEdtSalvar = false;
        this.atualizarTabela(null);
        this.habilitarCampos(false);
        this.habilitarBotoes(true, false, true, true, false, true, true, false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlFundo = new javax.swing.JPanel();
        pnlTitulo = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnVoltar = new javax.swing.JButton();
        pnlNovo = new javax.swing.JPanel();
        btnNovo = new javax.swing.JButton();
        pnlCancelar = new javax.swing.JPanel();
        btnCancelar = new javax.swing.JButton();
        pnlEditar = new javax.swing.JPanel();
        btnEditar = new javax.swing.JButton();
        pnlExcluir = new javax.swing.JPanel();
        btnExcluir = new javax.swing.JButton();
        pnlSalvar = new javax.swing.JPanel();
        btnSalvar = new javax.swing.JButton();
        pnlResetar = new javax.swing.JPanel();
        btnResetar = new javax.swing.JButton();
        pnlConsultar = new javax.swing.JPanel();
        btnConsultar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        grdUsuarios = new javax.swing.JTable();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        edtId = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtLog = new javax.swing.JTextArea();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        cbxTipo = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        edtValor = new javax.swing.JTextField();
        ftxCPF = new javax.swing.JFormattedTextField();
        edtLocalID = new javax.swing.JTextField();
        ftxData = new javax.swing.JFormattedTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnlFundo.setBackground(new java.awt.Color(0, 0, 48));
        pnlFundo.setForeground(new java.awt.Color(0, 0, 51));

        pnlTitulo.setBackground(new java.awt.Color(0, 153, 153));

        jLabel1.setFont(new java.awt.Font("Verdana", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Registrar Serviço");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        btnVoltar.setBackground(new java.awt.Color(0, 0, 0));
        btnVoltar.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        btnVoltar.setForeground(new java.awt.Color(255, 255, 255));
        btnVoltar.setText("Voltar");
        btnVoltar.setBorderPainted(false);
        btnVoltar.setContentAreaFilled(false);
        btnVoltar.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        btnVoltar.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnVoltar.setPreferredSize(new java.awt.Dimension(61, 50));
        btnVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlTituloLayout = new javax.swing.GroupLayout(pnlTitulo);
        pnlTitulo.setLayout(pnlTituloLayout);
        pnlTituloLayout.setHorizontalGroup(
            pnlTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlTituloLayout.createSequentialGroup()
                .addGap(341, 341, 341)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 507, Short.MAX_VALUE)
                .addGap(340, 340, 340)
                .addComponent(btnVoltar, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        pnlTituloLayout.setVerticalGroup(
            pnlTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTituloLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel1)
                .addContainerGap(16, Short.MAX_VALUE))
            .addComponent(btnVoltar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pnlNovo.setBackground(new java.awt.Color(0, 153, 153));
        pnlNovo.setPreferredSize(new java.awt.Dimension(95, 50));

        btnNovo.setFont(new java.awt.Font("Verdana", 0, 24)); // NOI18N
        btnNovo.setForeground(new java.awt.Color(255, 255, 255));
        btnNovo.setText("Novo");
        btnNovo.setContentAreaFilled(false);
        btnNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNovoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlNovoLayout = new javax.swing.GroupLayout(pnlNovo);
        pnlNovo.setLayout(pnlNovoLayout);
        pnlNovoLayout.setHorizontalGroup(
            pnlNovoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnNovo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pnlNovoLayout.setVerticalGroup(
            pnlNovoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnNovo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pnlCancelar.setBackground(new java.awt.Color(0, 153, 153));
        pnlCancelar.setPreferredSize(new java.awt.Dimension(135, 50));

        btnCancelar.setFont(new java.awt.Font("Verdana", 0, 24)); // NOI18N
        btnCancelar.setForeground(new java.awt.Color(255, 255, 255));
        btnCancelar.setText("Cancelar");
        btnCancelar.setContentAreaFilled(false);
        btnCancelar.setPreferredSize(new java.awt.Dimension(135, 50));
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlCancelarLayout = new javax.swing.GroupLayout(pnlCancelar);
        pnlCancelar.setLayout(pnlCancelarLayout);
        pnlCancelarLayout.setHorizontalGroup(
            pnlCancelarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnCancelar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pnlCancelarLayout.setVerticalGroup(
            pnlCancelarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnCancelar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pnlEditar.setBackground(new java.awt.Color(0, 153, 153));
        pnlEditar.setPreferredSize(new java.awt.Dimension(101, 50));

        btnEditar.setFont(new java.awt.Font("Verdana", 0, 24)); // NOI18N
        btnEditar.setForeground(new java.awt.Color(255, 255, 255));
        btnEditar.setText("Editar");
        btnEditar.setContentAreaFilled(false);
        btnEditar.setPreferredSize(new java.awt.Dimension(101, 50));
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlEditarLayout = new javax.swing.GroupLayout(pnlEditar);
        pnlEditar.setLayout(pnlEditarLayout);
        pnlEditarLayout.setHorizontalGroup(
            pnlEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnEditar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pnlEditarLayout.setVerticalGroup(
            pnlEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnEditar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pnlExcluir.setBackground(new java.awt.Color(0, 153, 153));
        pnlExcluir.setPreferredSize(new java.awt.Dimension(111, 50));

        btnExcluir.setFont(new java.awt.Font("Verdana", 0, 24)); // NOI18N
        btnExcluir.setForeground(new java.awt.Color(255, 255, 255));
        btnExcluir.setText("Excluir");
        btnExcluir.setContentAreaFilled(false);
        btnExcluir.setPreferredSize(new java.awt.Dimension(111, 50));
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlExcluirLayout = new javax.swing.GroupLayout(pnlExcluir);
        pnlExcluir.setLayout(pnlExcluirLayout);
        pnlExcluirLayout.setHorizontalGroup(
            pnlExcluirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnExcluir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pnlExcluirLayout.setVerticalGroup(
            pnlExcluirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnExcluir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pnlSalvar.setBackground(new java.awt.Color(0, 153, 153));
        pnlSalvar.setPreferredSize(new java.awt.Dimension(107, 50));

        btnSalvar.setFont(new java.awt.Font("Verdana", 0, 24)); // NOI18N
        btnSalvar.setForeground(new java.awt.Color(255, 255, 255));
        btnSalvar.setText("Salvar");
        btnSalvar.setContentAreaFilled(false);
        btnSalvar.setPreferredSize(new java.awt.Dimension(107, 50));
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlSalvarLayout = new javax.swing.GroupLayout(pnlSalvar);
        pnlSalvar.setLayout(pnlSalvarLayout);
        pnlSalvarLayout.setHorizontalGroup(
            pnlSalvarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnSalvar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pnlSalvarLayout.setVerticalGroup(
            pnlSalvarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnSalvar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pnlResetar.setBackground(new java.awt.Color(0, 153, 153));

        btnResetar.setFont(new java.awt.Font("Verdana", 0, 24)); // NOI18N
        btnResetar.setForeground(new java.awt.Color(255, 255, 255));
        btnResetar.setText("Resetar");
        btnResetar.setBorderPainted(false);
        btnResetar.setContentAreaFilled(false);
        btnResetar.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        btnResetar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnResetar.setPreferredSize(new java.awt.Dimension(123, 50));
        btnResetar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlResetarLayout = new javax.swing.GroupLayout(pnlResetar);
        pnlResetar.setLayout(pnlResetarLayout);
        pnlResetarLayout.setHorizontalGroup(
            pnlResetarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnResetar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pnlResetarLayout.setVerticalGroup(
            pnlResetarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnResetar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pnlConsultar.setBackground(new java.awt.Color(0, 153, 153));

        btnConsultar.setFont(new java.awt.Font("Verdana", 0, 24)); // NOI18N
        btnConsultar.setForeground(new java.awt.Color(255, 255, 255));
        btnConsultar.setText("Consultar");
        btnConsultar.setBorderPainted(false);
        btnConsultar.setContentAreaFilled(false);
        btnConsultar.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        btnConsultar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnConsultar.setPreferredSize(new java.awt.Dimension(147, 50));
        btnConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlConsultarLayout = new javax.swing.GroupLayout(pnlConsultar);
        pnlConsultar.setLayout(pnlConsultarLayout);
        pnlConsultarLayout.setHorizontalGroup(
            pnlConsultarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnConsultar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pnlConsultarLayout.setVerticalGroup(
            pnlConsultarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnConsultar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        grdUsuarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Tipo", "Valor", "Data", "Contratante", "Local"
            }
        ));
        grdUsuarios.setMaximumSize(new java.awt.Dimension(2147483647, 4000));
        jScrollPane1.setViewportView(grdUsuarios);

        jLabel2.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("ID:");

        jLabel3.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Tipo:");

        jLabel4.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Data:");

        edtId.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N

        jLabel7.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Log:");

        txtLog.setColumns(20);
        txtLog.setFont(new java.awt.Font("Monospaced", 0, 16)); // NOI18N
        txtLog.setRows(5);
        jScrollPane2.setViewportView(txtLog);

        jLabel8.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Contratante (CPF):");

        jLabel9.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Valor:");

        cbxTipo.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        cbxTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "<Selecione>", "Água", "Esgoto", "Inspeção", "Ligamento", "Desligamento" }));

        jLabel10.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Local (ID):");

        edtValor.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N

        ftxCPF.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        ftxCPF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ftxCPFActionPerformed(evt);
            }
        });

        edtLocalID.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N

        ftxData.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N

        javax.swing.GroupLayout pnlFundoLayout = new javax.swing.GroupLayout(pnlFundo);
        pnlFundo.setLayout(pnlFundoLayout);
        pnlFundoLayout.setHorizontalGroup(
            pnlFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlFundoLayout.createSequentialGroup()
                .addGroup(pnlFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlFundoLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(pnlFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlFundoLayout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addGroup(pnlFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(pnlFundoLayout.createSequentialGroup()
                                        .addComponent(jLabel8)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(ftxCPF, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(181, 181, 181))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlFundoLayout.createSequentialGroup()
                                        .addGroup(pnlFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(pnlFundoLayout.createSequentialGroup()
                                                .addComponent(jLabel4)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(ftxData, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jLabel9)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(edtValor, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(pnlFundoLayout.createSequentialGroup()
                                                .addComponent(jLabel2)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(edtId, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(34, 34, 34)
                                                .addComponent(jLabel3)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(cbxTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jLabel10)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(edtLocalID, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGap(17, 17, 17))))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlFundoLayout.createSequentialGroup()
                                    .addComponent(pnlNovo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(pnlCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(pnlEditar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(pnlExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(pnlSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 618, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(pnlFundoLayout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(jLabel7)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 353, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(pnlFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlFundoLayout.createSequentialGroup()
                        .addGap(152, 152, 152)
                        .addComponent(pnlConsultar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(54, 54, 54)
                        .addComponent(pnlResetar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlFundoLayout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(jScrollPane1)))
                .addGap(24, 24, 24))
        );
        pnlFundoLayout.setVerticalGroup(
            pnlFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlFundoLayout.createSequentialGroup()
                .addGroup(pnlFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pnlFundoLayout.createSequentialGroup()
                        .addComponent(pnlTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(pnlFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(pnlNovo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(pnlCancelar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(pnlEditar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(pnlExcluir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(pnlSalvar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(pnlFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(pnlConsultar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(pnlResetar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlFundoLayout.createSequentialGroup()
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addGroup(pnlFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(pnlFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(edtId, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE)
                                .addComponent(cbxTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(edtLocalID, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel2))
                        .addGroup(pnlFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlFundoLayout.createSequentialGroup()
                                .addGap(23, 23, 23)
                                .addGroup(pnlFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(ftxData, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel9)
                                    .addComponent(edtValor, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlFundoLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel4)))
                        .addGap(18, 18, 18)
                        .addGroup(pnlFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ftxCPF, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(145, 145, 145)
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(pnlFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7)))
                    .addComponent(jScrollPane1))
                .addGap(39, 39, 39))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlFundo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlFundo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    public void formatarCampos(){
        try {
            this.edtId.setDocument(new PadraoNumeros());
            this.edtLocalID.setDocument(new PadraoNumeros());
            this.edtValor.setDocument(new PadraoNumeros());
            MaskFormatter maskData = new MaskFormatter("####-##-##");
            MaskFormatter maskCPF = new MaskFormatter("###.###.###-##");
            maskData.install(ftxData);
            maskCPF.install(ftxCPF);
            this.txtLog.setEditable(false);
            this.atualizarLog("Programa iniciado.");
        } catch (ParseException ex) {
            Logger.getLogger(FrCadastroServico.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    public boolean validarCPF(String cpf){
        int digito1 = 0, digito2 = 0, calculoDigito1 = 0, calculoDigito2 = 0, j = 10, z = 11;
        boolean repetido = true;
        digito1 = Integer.parseInt(cpf.substring(12, 13));
        digito2 = Integer.parseInt(cpf.substring(13, 14));
        cpf = cpf.substring(0, 3) + cpf.substring(4, 7) + cpf.substring(8, 11);
        int[] arrayCPF = new int[9];
        for(int i = 0; i < arrayCPF.length; i++) {
            arrayCPF[i] = Integer.parseInt(cpf.substring(i, i+1));
            calculoDigito1 += j * arrayCPF[i];
            j--;
            calculoDigito2 += z * arrayCPF[i];
            z--;
            if (arrayCPF[0] != arrayCPF[1] && repetido) {
                repetido = false;
            }        
        }
        calculoDigito2 += z * digito1;
        calculoDigito1 = (calculoDigito1 * 10) % 11;
        calculoDigito2 = (calculoDigito2 * 10) % 11;
        
        if (calculoDigito1 == 10) {
            calculoDigito1 = 0;
        }
        if (calculoDigito2 == 10) {
            calculoDigito2 = 0;
        }
        if(calculoDigito1 != digito1 || calculoDigito2 != digito2 || repetido == true){
            return false;
        }else{
            return true;
        }
    }
    
    public boolean validarCampos(){
        if(edtId.getText().replace(" ","").equals("")){
            JOptionPane.showMessageDialog(rootPane, "Por favor, digite o ID corretamente.");
            edtId.requestFocus();
            return false;
        }else{
            if(servicoController.existe(edtId.getText()) == true && flagEdtSalvar == false){
                JOptionPane.showMessageDialog(rootPane, "ID já cadastrado.");
                edtId.setText("");
                edtId.requestFocus();
                return false;
            }
        }if(cbxTipo.getSelectedItem().toString().equals("<Selecione>")){
            JOptionPane.showMessageDialog(rootPane, "Por favor selecione um tipo.");
            cbxTipo.requestFocus();
            return false;
        }if(ftxCPF.getText().replace(" ","").length() < 14){
            JOptionPane.showMessageDialog(rootPane, "Por favor, digite o CPF corretamente.");
            ftxCPF.requestFocus();
            return false;
        }else{
            if(!validarCPF(ftxCPF.getText())){
                JOptionPane.showMessageDialog(rootPane, "CPF Inválido!");
                ftxCPF.setText("");
                ftxCPF.requestFocus();
                return false;
            }
        }if(edtLocalID.getText().replace(" ","").equals("")){
            JOptionPane.showMessageDialog(rootPane, "Por favor, digite o local corretamente.");
            edtLocalID.requestFocus();
            return false;
        }if(ftxData.getText().replace(" ","").length() < 10){
            JOptionPane.showMessageDialog(rootPane, "Por favor, digite a data corretamente.");
            ftxData.requestFocus();
            return false;
        }if(edtValor.getText().replace(" ","").equals("")){
            JOptionPane.showMessageDialog(rootPane, "Por favor, digite o valor corretamente.");
            edtValor.requestFocus();
            return false;
        }
        return true;
    }
    
    public void habilitarBotoes(boolean novo, boolean cancelar, boolean editar, boolean excluir, boolean salvar, boolean consultar, boolean  voltar, boolean resetar){
        this.btnNovo.setEnabled(novo);
        this.btnCancelar.setEnabled(cancelar);
        this.btnEditar.setEnabled(editar);
        this.btnExcluir.setEnabled(excluir);
        this.btnSalvar.setEnabled(salvar);
        this.btnConsultar.setEnabled(consultar);
        this.btnVoltar.setEnabled(voltar);
        this.btnResetar.setEnabled(resetar);
    }
    
    public void resetFields(){
        edtId.setText("");
        cbxTipo.setSelectedItem("<Selecione>");
        edtLocalID.setText("");
        ftxData.setText("");
        edtValor.setText("");
        ftxCPF.setText("");
    }
    
    public void habilitarCampos(boolean flag){
        for(int i=0; i<pnlFundo.getComponents().length; i++)
            pnlFundo.getComponent(i).setEnabled(flag);
    }
    
    public void atualizarTabela(Object [] usr) {
        ArrayList<Object []> arrayObj = servicoController.buscarServico(usr);
        DefaultTableModel dtm = (DefaultTableModel) grdUsuarios.getModel();
        dtm.setNumRows(0);
        for (int i=0; i<arrayObj.size(); i++) {
            dtm.addRow(new Object[]{
                arrayObj.get(i)[0], arrayObj.get(i)[1], arrayObj.get(i)[2], arrayObj.get(i)[3], arrayObj.get(i)[4], arrayObj.get(i)[5]});
        }
        grdUsuarios.setModel(dtm);
    }
    
    public void atualizarLog(String s){
        this.txtLog.setText(this.txtLog.getText() + s + "\n");
    }
    
    public void update(){
        try {
            servico = new Object[6];
            SimpleDateFormat formatoData = new SimpleDateFormat("yyyy-MM-dd");
            Date data = formatoData.parse(ftxData.getText());
            java.sql.Date datasql = new java.sql.Date(data.getTime());  
            servico[0] = Integer.parseInt(edtId.getText());
            servico[1] = cbxTipo.getSelectedItem().toString();
            servico[2] = edtLocalID.getText();
            servico[3] = datasql;
            servico[4] = ftxCPF.getText();
            servico[5] = Float.parseFloat(edtValor.getText());
            servicoController.alterar(servico);
        } catch (ParseException ex) {
            Logger.getLogger(FrCadastroServico.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        if(validarCampos()){
            try {
                if(this.flagEdtSalvar == true){
                    this.update();
                    this.atualizarLog("Serviço " + edtId.getText() + " alterado.");
                }else{
                    servico = new Object[6];
                    SimpleDateFormat formatoData = new SimpleDateFormat("yyyy-MM-dd");
                    Date data = formatoData.parse(ftxData.getText());
                    java.sql.Date datasql = new java.sql.Date(data.getTime());  
                    servico[0] = Integer.parseInt(edtId.getText());
                    servico[1] = cbxTipo.getSelectedItem().toString();
                    servico[2] = edtLocalID.getText();
                    servico[3] = datasql;
                    servico[4] = ftxCPF.getText();
                    servico[5] = Float.parseFloat(edtValor.getText());
                    servicoController.inserir(servico);
                }
                this.atualizarTabela(null);
                this.habilitarCampos(false);
                this.habilitarBotoes(true, false, true, true, false, true, true, false);
                if(this.flagEdtSalvar == false){
                    this.atualizarLog("Serviço " + edtId.getText() + " salvo.");
                }
                this.resetFields();
            } catch (ParseException ex) {
                Logger.getLogger(FrCadastroServico.class.getName()).log(Level.SEVERE, null, ex);
            }
        }       
    }//GEN-LAST:event_btnSalvarActionPerformed

    private void btnNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovoActionPerformed
        this.habilitarBotoes(false, true, false, false, true, false, false, false);
        this.resetFields();
        this.habilitarCampos(true);
        this.edtId.requestFocus();
        this.flagCancelar = true;
        this.flagEdtSalvar = false;
    }//GEN-LAST:event_btnNovoActionPerformed

    private void btnVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarActionPerformed
        FrTelaPrincipal telaPrincipal = new FrTelaPrincipal();
        this.dispose();
    }//GEN-LAST:event_btnVoltarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        this.habilitarBotoes(true, false, true, true, false, true, true, false);
        if(this.flagCancelar == true){
            this.resetFields();
            this.habilitarCampos(false);
        }else if(this.flagCancelar == false){
            this.btnSalvarActionPerformed(evt);
            this.resetFields();
            this.habilitarCampos(false);
        }
        this.atualizarTabela(null);
        this.atualizarLog("Operação cancelada.");
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        servico = new Object[6];
        if(grdUsuarios.getSelectedRow() != -1){
            int id = (int) grdUsuarios.getValueAt(grdUsuarios.getSelectedRow(), 0);
            servico[0] = id;
            servico = servicoController.buscarServico(servico).get(0);
        }else{
            JOptionPane.showMessageDialog(rootPane, "Selecione um Serviço (clique na linha).");
        }if(servico != null){
            edtId.setText(servico[0].toString());
            cbxTipo.setSelectedItem(servico[1]);
            edtValor.setText(servico[2].toString());
            ftxData.setText(servico[3].toString());
            ftxCPF.setText(servico[4].toString());
            edtLocalID.setText(servico[5].toString());
            this.habilitarBotoes(false, true, false, false, true, false, false, false);
            this.habilitarCampos(true);
            edtId.setEnabled(false);
            this.flagCancelar = true;
            this.flagEdtSalvar = true;
        }
    }//GEN-LAST:event_btnEditarActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        int id = -1;
        servico = new Object[6];
        if(grdUsuarios.getSelectedRow() != -1){
            id = (int) grdUsuarios.getValueAt(grdUsuarios.getSelectedRow(), 0);
            servico[0] = id;
            servico = servicoController.buscarServico(servico).get(0);
        }if(servico != null){
            int op = JOptionPane.showConfirmDialog(rootPane, "Deseja realmente excluir?", "Escolha uma opção", JOptionPane.YES_NO_OPTION);
            if(op == JOptionPane.YES_OPTION){
                servicoController.excluir(servico);
                this.habilitarBotoes(true, false, true, true, false, true, true, false);
                this.atualizarTabela(null);
                this.resetFields();
                this.habilitarCampos(false);
                this.atualizarLog("Usuário " + id + " excluído.");
            }
        }else{
            JOptionPane.showMessageDialog(rootPane, "Selecione um Serviço (clique na linha).");
        }
    }//GEN-LAST:event_btnExcluirActionPerformed

    private void btnConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarActionPerformed
        int id = Integer.parseInt(JOptionPane.showInputDialog("Informe um ID: "));
        servico = new Object[6];
        servico[0] = id;
        servicoController.buscarServico(servico);
        if(id < 0){
            this.atualizarLog("Operação cancelada.");
        }else if(servico == null){
            JOptionPane.showMessageDialog(rootPane, "Serviço não encontrado.");
        }else{
            this.habilitarBotoes(true, false, true, true, false, false, true, true);
            this.habilitarCampos(false);
            this.flagCancelar = true;
            this.flagEdtSalvar = true;
            this.atualizarLog("Busca concluída");
            this.atualizarTabela(servico);
        }
    }//GEN-LAST:event_btnConsultarActionPerformed

    private void btnResetarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetarActionPerformed
        this.habilitarBotoes(true, false, true, true, false, true, true, false);
        this.atualizarTabela(null);
    }//GEN-LAST:event_btnResetarActionPerformed

    private void ftxCPFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ftxCPFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ftxCPFActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrCadastroServico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnConsultar;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnNovo;
    private javax.swing.JButton btnResetar;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JButton btnVoltar;
    private javax.swing.JComboBox<String> cbxTipo;
    private javax.swing.JTextField edtId;
    private javax.swing.JTextField edtLocalID;
    private javax.swing.JTextField edtValor;
    private javax.swing.JFormattedTextField ftxCPF;
    private javax.swing.JFormattedTextField ftxData;
    private javax.swing.JTable grdUsuarios;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JPanel pnlCancelar;
    private javax.swing.JPanel pnlConsultar;
    private javax.swing.JPanel pnlEditar;
    private javax.swing.JPanel pnlExcluir;
    private javax.swing.JPanel pnlFundo;
    private javax.swing.JPanel pnlNovo;
    private javax.swing.JPanel pnlResetar;
    private javax.swing.JPanel pnlSalvar;
    private javax.swing.JPanel pnlTitulo;
    private javax.swing.JTextArea txtLog;
    // End of variables declaration//GEN-END:variables
}
